name: CI

on:
  push:
    branches: [ main, release ]
  pull_request:
    branches: [ main, release ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn compile

      - name: Lint
        run: yarn tslint
